### ISSUE TITLE
i can not  see iPhone screen projected on the browser by visiting http://127.0.0.1:8100/inspector . The IDC is either. Thanks for your help , waiting  for  your reply.

### ISSUE THREAD

**Issue by luoting0323** [AirtestProject/iOS-Tagent#98] opened 2019-10-10 13:19 UTC
![image](https://user-images.githubusercontent.com/56343996/66572221-271e3b00-eba3-11e9-9032-8a41c4ac44b0.png)
![image](https://user-images.githubusercontent.com/56343996/66572238-33a29380-eba3-11e9-80b4-e27f39429efe.png)

**Comment by EraChen233** [comment] 2019-10-10 13:33
What is the version of your xcode and ios os?

**Comment by EraChen233** [comment] 2019-10-10 13:35
Duplicate of #99

**Closed by EraChen233** 2019-10-10 13:35 UTC
