### ISSUE TITLE
多提交了 ，如何删除？

### ISSUE THREAD

**Issue by houzhimeng** [AirtestProject/iOS-Tagent#36] opened 2019-04-02 09:31 UTC
2019-04-02 17:26:28.574422+0800 WebDriverAgentRunner-Runner[3519:923556] Running tests...
2019-04-02 17:26:28.703991+0800 WebDriverAgentRunner-Runner[3519:923556] 未能载入软件包“WebDriverAgentRunner”。 请尝试重新安装软件包。
2019-04-02 17:26:28.704128+0800 WebDriverAgentRunner-Runner[3519:923556] (dlopen(/var/containers/Bundle/Application/70072B7A-0574-48A1-8E86-A9ED438862F7/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner, 265): Symbol not found: _OBJC_CLASS_$_XCEventGenerator
  Referenced from: /private/var/containers/Bundle/Application/70072B7A-0574-48A1-8E86-A9ED438862F7/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Expected in: /private/var/containers/Bundle/Application/70072B7A-0574-48A1-8E86-A9ED438862F7/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest
 in /private/var/containers/Bundle/Application/70072B7A-0574-48A1-8E86-A9ED438862F7/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib)

**Comment by EraChen233** [comment] 2019-04-04 03:35
Duplicate of #34

**Closed by EraChen233** 2019-04-04 03:35 UTC
